# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
