name: "Shared Rust toolchain setting up steps"
description: "Shared Rust toolchain setting up steps"
inputs:
  cache:
    description: "to cache or not to cache, that is the question"
    required: false
    default: "true"
  rust_toolchain_version:
    description: "Rust toolchain version"
    required: true
  targets:
    description: "pass targets to the rust-toolchain installer"
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # overwriting default rust-toolchain
        echo ${{ inputs.rust_toolchain_version }} > rust-toolchain
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust_toolchain_version }}
        components: clippy, rustfmt
        targets: ${{ inputs.targets }}
    - if: ${{ inputs.cache == 'true' }}
      uses: Swatinem/rust-cache@v2
