[package]
name = "saffron"
version = "0.1.0"
description = "He who controls the spice controls the universe."
repository = "https://github.com/o1-labs/proof-systems"
homepage = "https://o1-labs.github.io/proof-systems/"
documentation = "https://o1-labs.github.io/proof-systems/rustdoc/"
readme = "README.md"
edition = "2021"
license = "Apache-2.0"

# [lib]
# path = "src/lib.rs"

[[bin]]
name = "saffron"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
ark-ff.workspace = true
ark-serialize = { workspace = true, features = ["derive"]}
clap = { workspace = true, features = ["derive"] }
mina-curves.workspace = true
o1-utils.workspace = true


[dev-dependencies]
ark-std.workspace = true
proptest.workspace = true