name: MIPS Build, Test, and Package

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_toolchain_version: ["1.74"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache apt packages
      id: apt-cache
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt/archives/*.deb
        key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/mips-build.yml') }}

    - name: Install MIPS tools
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils-mips-linux-gnu

    - name: Build MIPS programs
      run: make build-mips-programs

    - name: Use shared Rust toolchain setting up steps
      uses: ./.github/actions/toolchain-shared
      with:
        rust_toolchain_version: ${{ matrix.rust_toolchain_version }}

    - name: Test interpreter against mips programs
      run: |
        cargo test --features open_mips --test test_mips_elf -- --nocapture

    - name: Create tar archive
      run: |
        cd o1vm/resources/programs/mips
        tar -czf mips-binaries.tar.gz bin/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mips-binaries
        path: o1vm/resources/programs/mips/mips-binaries.tar.gz