name: Post an inline text message
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  run:
    name: Leave a kind message after updates
    runs-on: ubuntu-latest
    steps:
      - name: Greet the reader
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Hello World!"