name: Wasm

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-wasm:
    name: Build WebAssembly code

    runs-on: ["ubuntu-latest"]

    strategy:
      matrix:
        rust_toolchain_version: ["nightly-2024-06-13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use shared Rust toolchain setting up steps
        uses: ./.github/actions/toolchain-shared
        with:
          rust_toolchain_version: ${{ matrix.rust_toolchain_version }}
          targets: wasm32-unknown-unknown

      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack@0.12.1

      - shell: bash
        run: rustup component add rust-src

      - name: Build the WebAssembly for the web
        env:
          WASM_RUSTFLAGS: "-C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-arg=--max-memory=4294967296"
        run: wasm-pack build --target web --out-dir target/web plonk-wasm -- -Z build-std=panic_abort,std 

      - name: Build the WebAssembly for NodeJS
        env:
          WASM_RUSTFLAGS: "-C target-feature=+atomics,+bulk-memory,+mutable-globals -C link-arg=--max-memory=4294967296"
        run: wasm-pack build --target nodejs --out-dir target/nodejs plonk-wasm -- -Z build-std=panic_abort,std --features nodejs
